### ISSUE TITLE
doc fruitful forums

### ISSUE THREAD

**Issue by josephholsten** [fruitfuljs/docs#4]
it's important to specify where the Code of Conduct applies and is enforced. I assume all repos under https://github.com/fruitfuljs qualify, but are there any other forums?
- chat rooms
- mailing lists
- events
- twitter accounts?

**Comment by pup** [comment]
hi! this is specified in the code of conduct itself:

```
This Code of Conduct applies both within spaces involving this project and in other spaces involving community members. This includes the repository, its Pull Requests and Issue tracker, its Twitter community, private email communications in the context of the project, and any events where members of the project are participating, as well as adjacent communities and venues affecting the project's members.
```

(see https://github.com/fruitfuljs/website/blob/master/CODE_OF_CONDUCT.md#scope)

**Comment by josephholsten** [comment]
would it be useful to explicitly link to those forums? Is there not an chat forum, maybe slack, gitter or irc? 

I'm a little uncertain of how enforceable "any events where members of the project are participating" is, but I don't quite know how it could be improved.

**Comment by pup** [comment]
yeah, there currently isn't any explicit discussion spaces (apart from normal social networks) so right now it's useless to link those separately

**Comment by josephholsten** [comment]
great, then my whole point is moot!
